alias ls='ls -al --color=auto'
alias l='ls -l'
alias ll='ls -l'
alias la="ls -laF"
alias lh='ls -lh'

alias grep='grep --color=auto'
alias c='grep -rnI '

cm () {
    echo "grep -rnI $@ --color=always | less -R"
    grep -rnI $@ --color=always | less -R
}

# Some shortcuts taken from:
# https://github.com/mathiasbynens/dotfiles/blob/master/.aliases

alias timer='echo "Timer started. Stop with Ctrl-D." && date && time cat && date'

alias publicip="dig +short myip.opendns.com @resolver1.opendns.com"

# Get week number
alias week='date +%V'

# URL-encode strings
alias urlencode='python -c "import sys, urllib as ul; print ul.quote_plus(sys.argv[1]);"'
