# enable color in terminal (mac os)
if [ "$(uname -s)" == "Darwin" ]
then
    export CLICOLOR="xterm"
fi

# enable color in terminal (linux)
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias grep='grep --color=auto'
fi

alias l='ls -l'
alias ll='ls -l'
alias la="ls -la"
alias lh='ls -lh'

alias grep='grep --color=auto'
alias c='grep -rnI '

cm () {
    echo "grep -rnI $@ --color=always | less -R"
    grep -rnI $@ --color=always | less -R
}

# Some shortcuts taken from:
# https://github.com/mathiasbynens/dotfiles/blob/master/.aliases

alias timer='echo "Timer started. Stop with Ctrl-D." && date && time cat && date'

alias publicip="dig +short myip.opendns.com @resolver1.opendns.com"

# Get week number
alias week='date +%V'

# URL-encode strings
alias urlencode='python -c "import sys, urllib as ul; print ul.quote_plus(sys.argv[1]);"'
